apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.useFullName }}
  name: {{ template "fullname" . }}
{{- else }}
  name: {{ template "name" . }}
{{- end }}
  annotations:
{{- if .Values.config.annotations }}
{{ toYaml .Values.config.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.config.labels }}
{{ toYaml .Values.config.labels | indent 4 }}
{{- end }}
{{- if .Values.matchLabels }}
{{ toYaml .Values.matchLabels | indent 4 }}
{{- end }}
data:
  config.yaml: |-
    client:
      clientID: {{.Values.client.clientID}}
      clientSecret: {{.Values.client.clientSecret}}
      domain: {{.Values.client.domain}}
      apiURL: {{.Values.client.apiURL}}
    enableCallbackDeletion: {{.Values.enableCallbackDeletion}}
    creationDelay: {{.Values.creationDelay}}
