apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{- if .Values.deployment.annotations }}
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 4 }}
{{- end }}
{{- if .Values.matchLabels }}
{{ toYaml .Values.matchLabels | indent 4 }}
{{- end }}
{{- if .Values.useFullName }}
  name: {{ template "fullname" . }}
{{- else }}
  name: {{ template "name" . }}
{{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name | quote }}
{{- if .Values.matchLabels }}
{{ toYaml .Values.matchLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
{{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 8 }}
{{- end }}
{{- if .Values.matchLabels }}
{{ toYaml .Values.matchLabels | indent 8 }}
{{- end }}
    spec:
      containers:
      - env:
      {{- if .Values.watchNamespace }}
        - name: KUBERNETES_NAMESPACE
          value: {{ .Values.watchNamespace | quote }}
      {{- end }}
        - name: CONFIG_FILE_PATH
          value: {{ .Values.configFilePath }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      {{- if .Values.useFullName }}
        name: {{ template "fullname" . }}
      {{- else }}
        name: {{ template "name" . }}
      {{- end }}
        volumeMounts:
        - mountPath: /etc/auth0-ingress-controller
          name: config-volume
      serviceAccountName: {{ template "serviceAccountName" . }}
      volumes:
      - configMap:
        {{- if .Values.useFullName }}
          name: {{ template "fullname" . }}
        {{- else }}
          name: {{ template "name" . }}
        {{- end }}
        name: config-volume
