{{- if and ( .Values.rbac.create ) (.Values.watchNamespace) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
{{- if .Values.useFullName }}
  name: {{ template "fullname" . }}-role-binding
{{- else }}
  name: {{ template "name" . }}-role-binding
{{- end }}
  namespace: {{ .Values.watchNamespace | quote }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.rbac.labels }}
{{ toYaml .Values.rbac.labels | indent 4 }}
{{- end }}
{{- if .Values.matchLabels }}
{{ toYaml .Values.matchLabels | indent 4 }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
{{- if .Values.useFullName }}
  name: {{ template "fullname" . }}-role
{{- else }}
  name: {{ template "name" . }}-role
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ template "serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
