name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Get docker buildx
      run: |
        mkdir -p ~/.docker/cli-plugins/
        wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-arm64 -O ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build app
      run: make linux

    - name: Push the image to DockerHub
      run: docker login -u savealive -p "${DOCKERHUB_PASSWORD}"
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker container image
      run: docker buildx build --push -t savealive/auth0-ingress-controller:latest .

